
---
apiVersion: v1
kind: Service
metadata:
  name: multitool-web
  labels:
    app: multitool-web
    version: 1.0.0
spec:
  type: NodePort
  ports:
    - name: multitool-web
      port: 8080
      targetPort: webui
      nodePort: 30080
  selector:
    app: multitool-web
---